name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - NickName73
body:
  - type: markdown
    attributes:
      value: |
        Test
  - type: textarea
    id: bug
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
